fixtures:
  repositories:
    apt:
      repo: git://github.com/puppetlabs/puppetlabs-apt.git
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
    yumrepo_core:
      repo: git://github.com/puppetlabs/puppetlabs-yumrepo_core
      puppet_version: ">= 6.0.0"
    # Need by postgresql
    augeas_core:
      repo: git://github.com/puppetlabs/puppetlabs-augeas_core
      puppet_version: ">= 6.0.0"
    # Need by postgresql
    concat:
      repo: git://github.com/puppetlabs/puppetlabs-concat.git
    postgresql:
      repo: git://github.com/puppetlabs/puppetlabs-postgresql.git
    archive:
      repo: git://github.com/voxpupuli/puppet-archive.git
    windows_env:
      repo: git://github.com/voxpupuli/puppet-windows_env.git
  symlinks:
    sensu: "#{source_dir}"
